class ElementNames:
    CREATE_NAME = "1. Create"
    AT_DOCTOR_NAME = "2. Doctor"
    CHOOSE_LAB_OR_PALATA_NAME = "3. Transition Lab or Palata"
    DOCTOR_TO_LAB_NAME = "4. From Doctor to Lab"
    AT_LAB_NAME = "5. Laboratory"
    AT_REGISTRY_NAME = "6. Registry in Lab"
    TO_PALATA_NAME = "7. To Palata"
    TO_DOCTOR_OR_OUT_NAME = "8. To Doctor or OUT"
    FROM_LAB_TO_DOCTOR_NAME = "9. From Lab to Doctor"
